# To run this check locally, install SkyWalking Eyes somehow
# (https://github.com/apache/skywalking-eyes). On macOS you can `brew install
# license-eye` and run `license-eye header check` or `license-eye header fix`.

name: license-check

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  license:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Check License Header
        uses: apache/skywalking-eyes/header@a196742f472feaffafea537ce5a2a4c3c53a8de4 # v0.9.0
