# To run this check locally, install SkyWalking Eyes somehow
# (https://github.com/apache/skywalking-eyes). On macOS you can `brew install
# license-eye` and run `license-eye header check` or `license-eye header fix`.

name: license-check

on:
  push:
    branches: [main]
  pull_request:

jobs:
  license:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Check License Header
        uses: apache/skywalking-eyes/header@61275cc80d0798a405cb070f7d3a8aaf7cf2c2c1 # v0.8.0
